---
title: "Análisis espacial de los delitos en Costa Rica; generación de un Dashboard interactivo"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
```

```{r carga de paquetes}
### Carga de paquetes:
library(dplyr)
library(ggplot2)
library(ggthemes)
library(plotly)
library(DT)
library(readr)
library(readxl)
library(lubridate)
library(tidyverse)
library(sf)
library(leaflet)
library(flexdashboard)
library(stringi)

```

Página 1 
===============================================================

```{r carga de datos}
Est_pol <-
read_xls("estadisticaspoliciales2021.xls") 

cantones <-
  st_read(
    dsn = "cantones_simplificados.geojson",
    quiet = TRUE
  ) %>%
  st_transform(4326) # transformación a WGS84
```


Column {data-width=550}
-----------------------------------------------------------------------

### Incidencia del crimen en los cantones de Costa Rica

```{r generación del mapa}
# En el data frame de cantones
cantones <-
  cantones %>%
  mutate(canton_normalizado = tolower(stri_trans_general(canton, id = "Latin-ASCII")))

# En el data frame de delitos
Est_pol <-
  Est_pol %>%
  mutate(canton_normalizado = tolower(stri_trans_general(Canton, id = "Latin-ASCII")))

Est_pol %>%
  left_join(
    dplyr::select(st_drop_geometry(cantones),
                  canton_normalizado, cod_canton),
    by = "canton_normalizado",
    copy = FALSE,
    keep = FALSE
  ) %>%
  filter(is.na(cod_canton) & canton_normalizado != "desconocido") %>% # los cod_canton = NA son los que no están en el data frame de cantones
  distinct(canton_normalizado) # se despliegan solo los nombres de cantones diferentes

# Corrección de nombres de cantones en delitos
Est_pol <-
  Est_pol %>%
  mutate(Canton = if_else(Canton == "LEON CORTES", "LEON CORTES CASTRO", Canton)) %>%
  mutate(Canton = if_else(Canton == "VASQUEZ DE CORONADO", "VAZQUEZ DE CORONADO", Canton))

# Se realiza nuevamente esta operación para reflejar los cambios en los nombres de cantones
Est_pol <-
  Est_pol %>%
  mutate(canton_normalizado = tolower(stri_trans_general(Canton, id = "Latin-ASCII")))

# Revisión
Est_pol %>%
  left_join(
    dplyr::select(st_drop_geometry(cantones),
                  canton_normalizado, cod_canton),
    by = "canton_normalizado",
    copy = FALSE,
    keep = FALSE
  ) %>%
  filter(is.na(cod_canton) & canton_normalizado != "desconocido") %>% # los cod_canton = NA son los que no están en el data frame de cantones
  distinct(canton_normalizado)

# Unión del código de cantón a Est_pol
Est_pol <-
  Est_pol %>%
  left_join(
    dplyr::select(
      st_drop_geometry(cantones),
      cod_canton,
      canton_normalizado
    ),
    by = "canton_normalizado",
    copy = FALSE,
    keep = FALSE
  )

# Conteo de registros por código de cantón

delitos_x_canton <-
  Est_pol %>%
  count(cod_canton, name = "delitos")

# Unión de cantidad de delitos por cantón a cantones

cantones_delitos <-
  cantones %>%
  left_join(
    delitos_x_canton,
    by = "cod_canton",
    copy = FALSE,
    keep = FALSE
  )

# Paleta de colores para los mapas

colores_cantones_delitos <-
  colorNumeric(palette = "Reds",
               domain = cantones_delitos$delitos,
               na.color = "transparent")

# Mapa leaflet de delitos en cantones

leaflet() %>%
  setView(# centro y nivel inicial de acercamiento
    lng = -84.19452,
    lat = 9.572735,
    zoom = 7) %>%
  addTiles(group = "OpenStreetMap") %>% # capa base
  addPolygons(
    # capa de polígonos
    data = cantones_delitos,
    fillColor = ~ colores_cantones_delitos(cantones_delitos$delitos),
    fillOpacity = 0.8,
    color = "black",
    stroke = TRUE,
    weight = 1.0,
    popup = paste(
      # ventana emergente
      paste(
        "<strong>Cantón:</strong>",
        cantones_delitos$canton
      ),
      paste(
        "<strong>Delitos:</strong>",
        cantones_delitos$delitos
      ),
      sep = '<br/>'
    ),
    group = "Delitos en cantones"
  ) %>%
  addLayersControl(
    # control de capas
    baseGroups = c("OpenStreetMap"),
    overlayGroups = c("Delitos en cantones")
  ) %>%
  addLegend(
    # leyenda
    position = "bottomleft",
    pal = colores_cantones_delitos,
    values = cantones_delitos$delitos,
    group = "Delitos",
    title = "Cantidad de delitos"
  )

```

Column {data-width=450}
-----------------------------------------------------------------------

### Cantidad de delitos por tipo de delito

```{r Gráfico de la cantidad de delitos por tipo de delito}
Delitos <-
Est_pol %>%
  count(Delito) %>%
  ggplot(aes(x = reorder(Delito, n), y = n)) + 
  geom_bar(stat = "identity") +
coord_flip() +
ggtitle("Cantidad de delitos por tipo de delito") + 
  xlab("Tipo de delito") + 
  ylab("Cantidad de delitos") + 
  theme_minimal()
ggplotly(Delitos) %>% 
  config(locale = 'es')
```

Página 2 
===============================================================

Column {data-width=550}
-----------------------------------------------------------------------

### Chart B: DT interactiva de las estadísticas policiales registradas por el (OIJ) en el 2021:

```{r }
Est_pol %>%
  dplyr::select(Delito, Fecha, Victima, Edad, Genero, Provincia, Canton) %>%
  datatable(colnames = c(
    "Delito",
    "Fecha",
    "Víctima",
    "Edad",
    "Género",
    "Provincia",
    "Cantón"
  ), options = list(pageLength = 5, language = list(url = '//cdn.datatables.net/plug-ins/1.10.11/i18n/Spanish.json')))

```

Column {data-width=450}
-----------------------------------------------------------------------
### Cantidad de delitos por tipo de victima

```{r Cantidad de delitos por tipo de victima}
Delitos_victimas <-
Est_pol %>%
  count(Delito) %>%
  ggplot(aes(x = reorder(Delito, n), y = n)) + 
  geom_bar(stat = "identity") +
  scale_fill_grey() +
coord_flip() +
ggtitle("Cantidad de delitos por tipo de victima") + 
  xlab("Tipo de delito") + 
  ylab("Victima") + 
  theme_minimal()
ggplotly(Delitos_victimas) %>% 
  config(locale = 'es')
```

Página 3 
===============================================================

Column {data-width=350}
-----------------------------------------------------------------------
### Delitos cometidos por mes del 2021 en Costa Rica

```{r}
Del_mes <- Est_pol %>%
  dplyr::select(Fecha, Delito, Hora)
```


```{r}
graph2 <- 
Del_mes %>% mutate(mes = month(Fecha, label = FALSE)) %>%
  ggplot() +
  geom_bar(aes(x = mes), fill = "darkolivegreen3", color = "gold") + 
  ggtitle("Cantidad de delitos por mes") + 
  xlab("Mes (1-11)") + 
  ylab("Cantidad") + 
  theme_minimal() 
ggplotly(graph2) %>%
  config(locale = 'es')
```

Column {data-width=650}
-----------------------------------------------------------------------
### Proporción de la ocurrencia de delitos por género en Costa Rica (2021)

```{r}
Propor_gen <- Est_pol %>%
  dplyr::select(Delito, Genero)
```

```{r}
Apiladas_propor_genero <-
  Propor_gen %>%
  ggplot(aes(x = Delito, fill = Genero)) + 
  geom_bar(position = "fill") +
  coord_flip() +
  ggtitle("Proporción de la ocurrencia de delitos por género") +
  xlab("Delito") +
  ylab("Proporción") +
  labs(fill = "Genero") +
  theme_minimal()

ggplotly(Apiladas_propor_genero) %>% config(locale = 'es')
```

